/**
 * This class is generated by jOOQ
 */
package ge.economy.law.model.tables.records;


import ge.economy.law.model.tables.Court;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CourtRecord extends UpdatableRecordImpl<CourtRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1543154563;

    /**
     * Setter for <code>public.court.court_id</code>.
     */
    public void setCourtId(Integer value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>public.court.court_id</code>.
     */
    public Integer getCourtId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for <code>public.court.name</code>.
     */
    public void setName(String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>public.court.name</code>.
     */
    public String getName() {
        return (String) getValue(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Court.COURT.COURT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Court.COURT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCourtId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourtRecord value1(Integer value) {
        setCourtId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourtRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourtRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourtRecord
     */
    public CourtRecord() {
        super(Court.COURT);
    }

    /**
     * Create a detached, initialised CourtRecord
     */
    public CourtRecord(Integer courtId, String name) {
        super(Court.COURT);

        setValue(0, courtId);
        setValue(1, name);
    }
}
