/**
 * This class is generated by jOOQ
 */
package ge.economy.law.model.tables.records;


import ge.economy.law.model.tables.CourtInstance;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourtInstanceRecord extends UpdatableRecordImpl<CourtInstanceRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = -922089029;

	/**
	 * Setter for <code>public.court_instance.instance_id</code>.
	 */
	public void setInstanceId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.court_instance.instance_id</code>.
	 */
	public Integer getInstanceId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.court_instance.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.court_instance.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CourtInstance.COURT_INSTANCE.INSTANCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return CourtInstance.COURT_INSTANCE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getInstanceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CourtInstanceRecord value1(Integer value) {
		setInstanceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CourtInstanceRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CourtInstanceRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CourtInstanceRecord
	 */
	public CourtInstanceRecord() {
		super(CourtInstance.COURT_INSTANCE);
	}

	/**
	 * Create a detached, initialised CourtInstanceRecord
	 */
	public CourtInstanceRecord(Integer instanceId, String name) {
		super(CourtInstance.COURT_INSTANCE);

		setValue(0, instanceId);
		setValue(1, name);
	}
}
