/**
 * This class is generated by jOOQ
 */
package ge.economy.law.model.tables.records;

import ge.economy.law.model.tables.EndResult;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EndResultRecord extends UpdatableRecordImpl<EndResultRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = 1971714591;

	/**
	 * Setter for <code>public.end_result.end_result_id</code>.
	 */
	public void setEndResultId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.end_result.end_result_id</code>.
	 */
	public Integer getEndResultId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.end_result.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.end_result.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return EndResult.END_RESULT.END_RESULT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return EndResult.END_RESULT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getEndResultId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EndResultRecord value1(Integer value) {
		setEndResultId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EndResultRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EndResultRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EndResultRecord
	 */
	public EndResultRecord() {
		super(EndResult.END_RESULT);
	}

	/**
	 * Create a detached, initialised EndResultRecord
	 */
	public EndResultRecord(Integer endResultId, String name) {
		super(EndResult.END_RESULT);

		setValue(0, endResultId);
		setValue(1, name);
	}
}
