/**
 * This class is generated by jOOQ
 */
package ge.economy.law.model;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;

import javax.annotation.Generated;


/**
 * Convenience access to all sequences in public
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Sequences {

    /**
     * The sequence <code>public.board_board_id_seq</code>
     */
    public static final Sequence<Long> BOARD_BOARD_ID_SEQ = new SequenceImpl<Long>("board_board_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.case_case_id_seq</code>
     */
    public static final Sequence<Long> CASE_CASE_ID_SEQ = new SequenceImpl<Long>("case_case_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.case_doc_doc_id_seq</code>
     */
    public static final Sequence<Long> CASE_DOC_DOC_ID_SEQ = new SequenceImpl<Long>("case_doc_doc_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.court_court_id_seq</code>
     */
    public static final Sequence<Long> COURT_COURT_ID_SEQ = new SequenceImpl<Long>("court_court_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.court_instance_instance_id_seq</code>
     */
    public static final Sequence<Long> COURT_INSTANCE_INSTANCE_ID_SEQ = new SequenceImpl<Long>("court_instance_instance_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.end_result_end_result_id_seq</code>
     */
    public static final Sequence<Long> END_RESULT_END_RESULT_ID_SEQ = new SequenceImpl<Long>("end_result_end_result_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.judge_judge_id_seq</code>
     */
    public static final Sequence<Long> JUDGE_JUDGE_ID_SEQ = new SequenceImpl<Long>("judge_judge_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.litigation_subject_litigation_subject_id_seq</code>
     */
    public static final Sequence<Long> LITIGATION_SUBJECT_LITIGATION_SUBJECT_ID_SEQ = new SequenceImpl<Long>("litigation_subject_litigation_subject_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.status_status_id_seq</code>
     */
    public static final Sequence<Long> STATUS_STATUS_ID_SEQ = new SequenceImpl<Long>("status_status_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_status_status_id_seq</code>
     */
    public static final Sequence<Long> USER_STATUS_STATUS_ID_SEQ = new SequenceImpl<Long>("user_status_status_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_type_type_id_seq</code>
     */
    public static final Sequence<Long> USER_TYPE_TYPE_ID_SEQ = new SequenceImpl<Long>("user_type_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_user_id_seq</code>
     */
    public static final Sequence<Long> USER_USER_ID_SEQ = new SequenceImpl<Long>("user_user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
