/**
 * This class is generated by jOOQ
 */
package ge.economy.law.model.tables;


import ge.economy.law.model.Keys;
import ge.economy.law.model.Public;
import ge.economy.law.model.tables.records.CourtRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Court extends TableImpl<CourtRecord> {

	private static final long serialVersionUID = 1319873249;

	/**
	 * The reference instance of <code>public.court</code>
	 */
	public static final Court COURT = new Court();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CourtRecord> getRecordType() {
		return CourtRecord.class;
	}

	/**
	 * The column <code>public.court.court_id</code>.
	 */
	public final TableField<CourtRecord, Integer> COURT_ID = createField("court_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.court.name</code>.
	 */
	public final TableField<CourtRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

	/**
	 * Create a <code>public.court</code> table reference
	 */
	public Court() {
		this("court", null);
	}

	/**
	 * Create an aliased <code>public.court</code> table reference
	 */
	public Court(String alias) {
		this(alias, COURT);
	}

	private Court(String alias, Table<CourtRecord> aliased) {
		this(alias, aliased, null);
	}

	private Court(String alias, Table<CourtRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CourtRecord, Integer> getIdentity() {
		return Keys.IDENTITY_COURT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CourtRecord> getPrimaryKey() {
		return Keys.COURT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CourtRecord>> getKeys() {
		return Arrays.<UniqueKey<CourtRecord>>asList(Keys.COURT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Court as(String alias) {
		return new Court(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Court rename(String name) {
		return new Court(name, null);
	}
}
