/**
 * This class is generated by jOOQ
 */
package ge.economy.law.model.tables;

import ge.economy.law.model.Keys;
import ge.economy.law.model.Public;
import ge.economy.law.model.tables.records.JudgeRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Judge extends TableImpl<JudgeRecord> {

	private static final long serialVersionUID = -1202964457;

	/**
	 * The reference instance of <code>public.judge</code>
	 */
	public static final Judge JUDGE = new Judge();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<JudgeRecord> getRecordType() {
		return JudgeRecord.class;
	}

	/**
	 * The column <code>public.judge.judge_id</code>.
	 */
	public final TableField<JudgeRecord, Integer> JUDGE_ID = createField("judge_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.judge.name</code>.
	 */
	public final TableField<JudgeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>public.judge.assistant</code>.
	 */
	public final TableField<JudgeRecord, String> ASSISTANT = createField("assistant", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.judge.assistant_phone</code>.
	 */
	public final TableField<JudgeRecord, String> ASSISTANT_PHONE = createField("assistant_phone", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>public.judge</code> table reference
	 */
	public Judge() {
		this("judge", null);
	}

	/**
	 * Create an aliased <code>public.judge</code> table reference
	 */
	public Judge(String alias) {
		this(alias, JUDGE);
	}

	private Judge(String alias, Table<JudgeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Judge(String alias, Table<JudgeRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<JudgeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_JUDGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<JudgeRecord> getPrimaryKey() {
		return Keys.JUDGE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<JudgeRecord>> getKeys() {
		return Arrays.<UniqueKey<JudgeRecord>>asList(Keys.JUDGE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Judge as(String alias) {
		return new Judge(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Judge rename(String name) {
		return new Judge(name, null);
	}
}
